name: TrainingFirstPlugin
version: '${project.version}'
main: greg.pirat1c.humiliation.HumiliationPlugin
api-version: 1.19
authors: [ P1rat1C ]

commands:
  spawnEntity:
    description: the operator start sucking
    aliases:
      - sosite
      - suckit
  humiliateMe:
    description: you' ve been humiliated
    aliases:
      - humiliationtime
      - humiliation time
  test:
    description: spawn something
    aliases:
      - tests
  spawn:
    description: teleport players on a spawn
  sethome:
    description: remembers the current coordinates
  home:
    description: teleport on your house
  kitslave:
    description: gives player kit slave
    aliases:
      - kit slave
  saskesword:

