name: TrainingFirstPlugin
version: '${project.version}'
main: greg.pirat1c.humiliation.HumiliationPlugin
api-version: 1.19
softdepend: [ ProtocolLib ]
authors: [ P1rat1C ]

commands:
  spawnEntity:
    description: the operator start sucking
    aliases:
      - sosite
      - suckit
  humiliateMe:
    description: you' ve been humiliated
    aliases:
      - humiliationtime
      - humiliation time
  test:
    description: spawn something
    aliases:
      - tests
  spawn:
    description: teleport players on a spawn
  sethome:
    description: remembers the current coordinates
  home:
    description: teleport on your house
  kitslave:
    description: gives player kit slave
    aliases:
      - kit slave
  saskesword:
    description: give the player sword
  shuriken:
    description: give the player shuriken
  bodyReplacement:
    description: bodyReplacemen with people people in your eyes trace (has distance limit)
  attractionGive:
    description: attraction item (for Saske)
  chidoryGive:
    description: chidory item ability (for Saske)
  sniperGive:
    description: lady nagan's sniper item ability
  flyGive:
    description: lady nagan's fly ability
  explosionGive:
    description: lady nagan's explode perk
  trapGive:
    description: lady nagan's trap
  ultraGiveLady:
    description: ulta lady nagan give
  waterShieldGive:
    description: quick wall for Ishigava
  waterBridgesGive:
    description: bridges for Ishigava
  lastBridgesGive:
    description: last WALL for Ishigava
  auraGive:
    description: aura ult for Ishigava
  pistolGive:
    description: fukuko's pistol gun
  bombZoneGive:
    description: fukuko's ult
  mortiraGive:
    description: fukuko's mortira
  setclass:
    usage: /setclass <LadyNagan|Swordsman|Sniper>
    description: Set your player class